# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataloader_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 30, 581, 211))
        self.textEdit.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color:rgb(0, 0, 255)")
        self.textEdit.setObjectName("textEdit")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 30, 221, 211))
        self.listView.setStyleSheet("font: italic 12pt \"Segoe UI\";")
        self.listView.setObjectName("listView")
        self.board = QtWidgets.QGroupBox(self.centralwidget)
        self.board.setGeometry(QtCore.QRect(20, 270, 811, 431))
        self.board.setTitle("")
        self.board.setObjectName("board")
        self.numBoard = QtWidgets.QGroupBox(self.board)
        self.numBoard.setGeometry(QtCore.QRect(30, 30, 361, 391))
        self.numBoard.setTitle("")
        self.numBoard.setObjectName("numBoard")
        self.b1 = QtWidgets.QPushButton(self.numBoard)
        self.b1.setGeometry(QtCore.QRect(20, 40, 81, 71))
        self.b1.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.numBoard)
        self.b2.setGeometry(QtCore.QRect(140, 40, 81, 71))
        self.b2.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.numBoard)
        self.b3.setGeometry(QtCore.QRect(260, 40, 81, 71))
        self.b3.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.numBoard)
        self.b4.setGeometry(QtCore.QRect(20, 130, 81, 71))
        self.b4.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.numBoard)
        self.b5.setGeometry(QtCore.QRect(140, 130, 81, 71))
        self.b5.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.numBoard)
        self.b6.setGeometry(QtCore.QRect(260, 130, 81, 71))
        self.b6.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(self.numBoard)
        self.b7.setGeometry(QtCore.QRect(20, 220, 81, 71))
        self.b7.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(self.numBoard)
        self.b8.setGeometry(QtCore.QRect(140, 220, 81, 71))
        self.b8.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.numBoard)
        self.b9.setGeometry(QtCore.QRect(260, 220, 81, 71))
        self.b9.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b9.setObjectName("b9")
        self.b0 = QtWidgets.QPushButton(self.numBoard)
        self.b0.setGeometry(QtCore.QRect(140, 310, 81, 71))
        self.b0.setStyleSheet("font: 75 18pt \"Arial\";")
        self.b0.setObjectName("b0")
        self.bDot = QtWidgets.QPushButton(self.numBoard)
        self.bDot.setGeometry(QtCore.QRect(20, 310, 81, 71))
        self.bDot.setStyleSheet("font: 18pt \"Agency FB\";")
        self.bDot.setObjectName("bDot")
        self.ClearB = QtWidgets.QPushButton(self.numBoard)
        self.ClearB.setGeometry(QtCore.QRect(260, 310, 81, 71))
        self.ClearB.setStyleSheet("font: 18pt \"Agency FB\";")
        self.ClearB.setObjectName("ClearB")
        self.toolBoard = QtWidgets.QGroupBox(self.board)
        self.toolBoard.setGeometry(QtCore.QRect(420, 30, 381, 391))
        self.toolBoard.setTitle("")
        self.toolBoard.setObjectName("toolBoard")
        self.multiple = QtWidgets.QPushButton(self.toolBoard)
        self.multiple.setGeometry(QtCore.QRect(30, 40, 51, 51))
        self.multiple.setStyleSheet("font: 75 18pt \"Arial\";")
        self.multiple.setObjectName("multiple")
        self.divise = QtWidgets.QPushButton(self.toolBoard)
        self.divise.setGeometry(QtCore.QRect(100, 40, 51, 51))
        self.divise.setStyleSheet("font: 75 18pt \"Arial\";")
        self.divise.setObjectName("divise")
        self.add = QtWidgets.QPushButton(self.toolBoard)
        self.add.setGeometry(QtCore.QRect(170, 40, 51, 51))
        self.add.setStyleSheet("font: 75 18pt \"Arial\";")
        self.add.setObjectName("add")
        self.subtract = QtWidgets.QPushButton(self.toolBoard)
        self.subtract.setGeometry(QtCore.QRect(240, 40, 51, 51))
        self.subtract.setStyleSheet("font: 75 18pt \"Arial\";")
        self.subtract.setObjectName("subtract")
        self.isEqual = QtWidgets.QPushButton(self.toolBoard)
        self.isEqual.setGeometry(QtCore.QRect(310, 40, 51, 51))
        self.isEqual.setStyleSheet("font: 75 18pt \"Arial\";")
        self.isEqual.setObjectName("isEqual")
        self.BiggerEqualB = QtWidgets.QPushButton(self.toolBoard)
        self.BiggerEqualB.setGeometry(QtCore.QRect(100, 110, 51, 51))
        self.BiggerEqualB.setStyleSheet("font: 75 18pt \"Arial\";")
        self.BiggerEqualB.setObjectName("BiggerEqualB")
        self.LOwerEqualB = QtWidgets.QPushButton(self.toolBoard)
        self.LOwerEqualB.setGeometry(QtCore.QRect(170, 110, 51, 51))
        self.LOwerEqualB.setStyleSheet("font: 75 18pt \"Arial\";")
        self.LOwerEqualB.setObjectName("LOwerEqualB")
        self.BiggerB = QtWidgets.QPushButton(self.toolBoard)
        self.BiggerB.setGeometry(QtCore.QRect(240, 110, 51, 51))
        self.BiggerB.setStyleSheet("font: 75 18pt \"Arial\";")
        self.BiggerB.setObjectName("BiggerB")
        self.lowerB = QtWidgets.QPushButton(self.toolBoard)
        self.lowerB.setGeometry(QtCore.QRect(30, 110, 51, 51))
        self.lowerB.setStyleSheet("font: 75 18pt \"Arial\";")
        self.lowerB.setObjectName("lowerB")
        self.isNotEqual = QtWidgets.QPushButton(self.toolBoard)
        self.isNotEqual.setGeometry(QtCore.QRect(310, 110, 51, 51))
        self.isNotEqual.setStyleSheet("font: 75 18pt \"Arial\";")
        self.isNotEqual.setObjectName("isNotEqual")
        self.absB = QtWidgets.QPushButton(self.toolBoard)
        self.absB.setGeometry(QtCore.QRect(30, 180, 51, 51))
        self.absB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.absB.setObjectName("absB")
        self.powerB = QtWidgets.QPushButton(self.toolBoard)
        self.powerB.setGeometry(QtCore.QRect(100, 180, 51, 51))
        self.powerB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.powerB.setObjectName("powerB")
        self.sqrtB = QtWidgets.QPushButton(self.toolBoard)
        self.sqrtB.setGeometry(QtCore.QRect(170, 180, 51, 51))
        self.sqrtB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.sqrtB.setObjectName("sqrtB")
        self.leftParen = QtWidgets.QPushButton(self.toolBoard)
        self.leftParen.setGeometry(QtCore.QRect(240, 180, 51, 51))
        self.leftParen.setStyleSheet("font: 10pt \"Agency FB\";")
        self.leftParen.setObjectName("leftParen")
        self.rightParen = QtWidgets.QPushButton(self.toolBoard)
        self.rightParen.setGeometry(QtCore.QRect(310, 180, 51, 51))
        self.rightParen.setStyleSheet("font: 10pt \"Agency FB\";")
        self.rightParen.setObjectName("rightParen")
        self.sinB = QtWidgets.QPushButton(self.toolBoard)
        self.sinB.setGeometry(QtCore.QRect(30, 250, 51, 51))
        self.sinB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.sinB.setObjectName("sinB")
        self.cosB = QtWidgets.QPushButton(self.toolBoard)
        self.cosB.setGeometry(QtCore.QRect(100, 250, 51, 51))
        self.cosB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.cosB.setObjectName("cosB")
        self.tanB = QtWidgets.QPushButton(self.toolBoard)
        self.tanB.setGeometry(QtCore.QRect(170, 250, 51, 51))
        self.tanB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.tanB.setObjectName("tanB")
        self.asinB = QtWidgets.QPushButton(self.toolBoard)
        self.asinB.setGeometry(QtCore.QRect(240, 250, 51, 51))
        self.asinB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.asinB.setObjectName("asinB")
        self.acosB = QtWidgets.QPushButton(self.toolBoard)
        self.acosB.setGeometry(QtCore.QRect(310, 250, 51, 51))
        self.acosB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.acosB.setObjectName("acosB")
        self.atanB = QtWidgets.QPushButton(self.toolBoard)
        self.atanB.setGeometry(QtCore.QRect(30, 320, 51, 51))
        self.atanB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.atanB.setObjectName("atanB")
        self.lnB = QtWidgets.QPushButton(self.toolBoard)
        self.lnB.setGeometry(QtCore.QRect(100, 320, 51, 51))
        self.lnB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.lnB.setObjectName("lnB")
        self.logB = QtWidgets.QPushButton(self.toolBoard)
        self.logB.setGeometry(QtCore.QRect(170, 320, 51, 51))
        self.logB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.logB.setObjectName("logB")
        self.minB = QtWidgets.QPushButton(self.toolBoard)
        self.minB.setGeometry(QtCore.QRect(240, 320, 51, 51))
        self.minB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.minB.setObjectName("minB")
        self.maxB = QtWidgets.QPushButton(self.toolBoard)
        self.maxB.setGeometry(QtCore.QRect(310, 320, 51, 51))
        self.maxB.setStyleSheet("font: 10pt \"Agency FB\";")
        self.maxB.setObjectName("maxB")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(730, 710, 93, 31))
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.runButton.setToolTip("")
        self.runButton.setStyleSheet("font: 12pt \"Bahnschrift SemiCondensed\";")
        self.runButton.setObjectName("runButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 710, 471, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.loadPath = QtWidgets.QPushButton(self.centralwidget)
        self.loadPath.setGeometry(QtCore.QRect(500, 710, 31, 31))
        self.loadPath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadPath.setToolTip("")
        self.loadPath.setStyleSheet("font: 12pt \"Bahnschrift SemiCondensed\";")
        self.loadPath.setObjectName("loadPath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionzoom_in = QtWidgets.QAction(MainWindow)
        self.actionzoom_in.setObjectName("actionzoom_in")
        self.actionzoom_out = QtWidgets.QAction(MainWindow)
        self.actionzoom_out.setObjectName("actionzoom_out")
        self.actionfull_extent = QtWidgets.QAction(MainWindow)
        self.actionfull_extent.setObjectName("actionfull_extent")
        self.actionpan = QtWidgets.QAction(MainWindow)
        self.actionpan.setObjectName("actionpan")
        self.actionopen_raster = QtWidgets.QAction(MainWindow)
        self.actionopen_raster.setObjectName("actionopen_raster")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyPYQGIS"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.bDot.setText(_translate("MainWindow", "·"))
        self.ClearB.setText(_translate("MainWindow", "Clear"))
        self.multiple.setText(_translate("MainWindow", "*"))
        self.divise.setText(_translate("MainWindow", "/"))
        self.add.setText(_translate("MainWindow", "+"))
        self.subtract.setText(_translate("MainWindow", "-"))
        self.isEqual.setText(_translate("MainWindow", "="))
        self.BiggerEqualB.setText(_translate("MainWindow", ">="))
        self.LOwerEqualB.setText(_translate("MainWindow", "<="))
        self.BiggerB.setText(_translate("MainWindow", ">"))
        self.lowerB.setText(_translate("MainWindow", "<"))
        self.isNotEqual.setText(_translate("MainWindow", "!="))
        self.absB.setText(_translate("MainWindow", "Abs("))
        self.powerB.setText(_translate("MainWindow", "Pow(^)"))
        self.sqrtB.setText(_translate("MainWindow", "Sqrt("))
        self.leftParen.setText(_translate("MainWindow", "("))
        self.rightParen.setText(_translate("MainWindow", ")"))
        self.sinB.setText(_translate("MainWindow", "sin("))
        self.cosB.setText(_translate("MainWindow", "cos("))
        self.tanB.setText(_translate("MainWindow", "tan("))
        self.asinB.setText(_translate("MainWindow", "Asin("))
        self.acosB.setText(_translate("MainWindow", "Acos("))
        self.atanB.setText(_translate("MainWindow", "Atan("))
        self.lnB.setText(_translate("MainWindow", "ln("))
        self.logB.setText(_translate("MainWindow", "log10("))
        self.minB.setText(_translate("MainWindow", "Min("))
        self.maxB.setText(_translate("MainWindow", "Max("))
        self.runButton.setText(_translate("MainWindow", "RUN"))
        self.loadPath.setText(_translate("MainWindow", "..."))
        self.actionopen_file.setText(_translate("MainWindow", "open file"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionzoom_in.setText(_translate("MainWindow", "zoom in"))
        self.actionzoom_out.setText(_translate("MainWindow", "zoom out"))
        self.actionfull_extent.setText(_translate("MainWindow", "full extent"))
        self.actionpan.setText(_translate("MainWindow", "pan"))
        self.actionopen_raster.setText(_translate("MainWindow", "open raster"))
