# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_FAST.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(429, 444)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_r = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_r.setObjectName("label_r")
        self.verticalLayout.addWidget(self.label_r)
        self.comboBox_r = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_r.setObjectName("comboBox_r")
        self.verticalLayout.addWidget(self.comboBox_r)
        self.label_g = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_g.setObjectName("label_g")
        self.verticalLayout.addWidget(self.label_g)
        self.comboBox_g = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_g.setObjectName("comboBox_g")
        self.verticalLayout.addWidget(self.comboBox_g)
        self.label_b = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_b.setObjectName("label_b")
        self.verticalLayout.addWidget(self.label_b)
        self.comboBox_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_b.setObjectName("comboBox_b")
        self.verticalLayout.addWidget(self.comboBox_b)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_color = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_color.setText("")
        self.label_color.setObjectName("label_color")
        self.horizontalLayout_3.addWidget(self.label_color)
        self.pushButton_color = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_color.setObjectName("pushButton_color")
        self.horizontalLayout_3.addWidget(self.pushButton_color)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.pushButton_name = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_name.setObjectName("pushButton_name")
        self.horizontalLayout.addWidget(self.pushButton_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_null = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_null.setText("")
        self.label_null.setObjectName("label_null")
        self.verticalLayout.addWidget(self.label_null)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.pushButton_ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_r.setText(_translate("Dialog", "R波段"))
        self.label_g.setText(_translate("Dialog", "G波段"))
        self.label_b.setText(_translate("Dialog", "B波段"))
        self.label_2.setText(_translate("Dialog", "选择角点显示颜色"))
        self.pushButton_color.setText(_translate("Dialog", "选择颜色"))
        self.label_name.setText(_translate("Dialog", "保存位置"))
        self.pushButton_name.setText(_translate("Dialog", "选择位置"))
        self.checkBox.setText(_translate("Dialog", "是否在完成后加入到图层中"))
        self.pushButton_ok.setText(_translate("Dialog", "执行"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))

