# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_lvbo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Dlg_lvbo_class(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(734, 656)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(390, 600, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_r = QtWidgets.QComboBox(Dialog)
        self.comboBox_r.setGeometry(QtCore.QRect(90, 50, 541, 22))
        self.comboBox_r.setObjectName("comboBox_r")
        self.comboBox_g = QtWidgets.QComboBox(Dialog)
        self.comboBox_g.setGeometry(QtCore.QRect(90, 130, 541, 22))
        self.comboBox_g.setObjectName("comboBox_g")
        self.comboBox_b = QtWidgets.QComboBox(Dialog)
        self.comboBox_b.setGeometry(QtCore.QRect(90, 210, 541, 22))
        self.comboBox_b.setObjectName("comboBox_b")
        self.label_r = QtWidgets.QLabel(Dialog)
        self.label_r.setGeometry(QtCore.QRect(90, 20, 72, 15))
        self.label_r.setObjectName("label_r")
        self.label_g = QtWidgets.QLabel(Dialog)
        self.label_g.setGeometry(QtCore.QRect(90, 100, 72, 15))
        self.label_g.setObjectName("label_g")
        self.label_b = QtWidgets.QLabel(Dialog)
        self.label_b.setGeometry(QtCore.QRect(90, 180, 72, 15))
        self.label_b.setObjectName("label_b")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(70, 610, 241, 19))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 600, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 550, 71, 21))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 550, 41, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(190, 550, 401, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(120, 490, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(80, 260, 201, 101))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(50, 30, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 60, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 380, 201, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 30, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 60, 131, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(410, 270, 241, 241))
        self.widget.setObjectName("widget")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setMaxLength(4)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setMaxLength(4)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_4.setMaxLength(4)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setMaxLength(4)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_6.setMaxLength(4)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_7.setMaxLength(4)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_8.setMaxLength(4)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(100, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_9.setMaxLength(4)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_10.setMaxLength(4)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.pushButton.raise_()
        self.comboBox_r.raise_()
        self.comboBox_g.raise_()
        self.comboBox_b.raise_()
        self.label_r.raise_()
        self.label_g.raise_()
        self.label_b.raise_()
        self.checkBox.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_name.raise_()
        self.radioButton_5.raise_()
        self.widget.raise_()

        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "执行"))
        self.label_r.setText(_translate("Dialog", "R波段"))
        self.label_g.setText(_translate("Dialog", "G波段"))
        self.label_b.setText(_translate("Dialog", "B波段"))
        self.checkBox.setText(_translate("Dialog", "是否在完成后加入到图层中"))
        self.pushButton_2.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "保存位置"))
        self.pushButton_3.setText(_translate("Dialog", "..."))
        self.radioButton_5.setText(_translate("Dialog", "自定义算子"))
        self.groupBox.setTitle(_translate("Dialog", "图像平滑"))
        self.radioButton.setText(_translate("Dialog", "均值滤波"))
        self.radioButton_2.setText(_translate("Dialog", "高斯平滑"))
        self.groupBox_2.setTitle(_translate("Dialog", "边缘提取"))
        self.radioButton_3.setText(_translate("Dialog", "Soble算子"))
        self.radioButton_4.setText(_translate("Dialog", "Laplacian算子"))
        self.lineEdit_2.setText(_translate("Dialog", "1/9"))
        self.lineEdit_3.setText(_translate("Dialog", "1/9"))
        self.lineEdit_4.setText(_translate("Dialog", "1/9"))
        self.lineEdit_5.setText(_translate("Dialog", "1/9"))
        self.lineEdit_6.setText(_translate("Dialog", "1/9"))
        self.lineEdit_7.setText(_translate("Dialog", "1/9"))
        self.lineEdit_8.setText(_translate("Dialog", "1/9"))
        self.lineEdit_9.setText(_translate("Dialog", "1/9"))
        self.lineEdit_10.setText(_translate("Dialog", "1/9"))
