# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1601, 945)
        desktop = QApplication.desktop()
        Dialog.move(desktop.width() * 0.066, desktop.height() * 0.040)
        self.main_treeView = QtWidgets.QTreeView(Dialog)
        self.main_treeView.setGeometry(QtCore.QRect(65, 186, 305, 665))
        self.main_treeView.setObjectName("main_treeView")
        self.main_wg_canvas = QtWidgets.QWidget(Dialog)
        self.main_wg_canvas.setGeometry(QtCore.QRect(420, 190, 1101, 695))
        self.main_wg_canvas.setObjectName("main_wg_canvas")
        self.main_progressBar = QtWidgets.QProgressBar(Dialog)
        self.main_progressBar.setGeometry(QtCore.QRect(80, 875, 211, 23))
        self.main_progressBar.setProperty("value", 24)
        self.main_progressBar.setTextVisible(False)
        self.main_progressBar.setObjectName("main_progressBar")
        self.main_pB_dk = QtWidgets.QPushButton(Dialog)
        self.main_pB_dk.setGeometry(QtCore.QRect(60, 50, 120, 45))
        self.main_pB_dk.setText("")
        self.main_pB_dk.setObjectName("main_pB_dk")
        self.main_pB_fd = QtWidgets.QPushButton(Dialog)
        self.main_pB_fd.setGeometry(QtCore.QRect(435, 50, 120, 45))
        self.main_pB_fd.setText("")
        self.main_pB_fd.setObjectName("main_pB_fd")
        self.main_pB_sx = QtWidgets.QPushButton(Dialog)
        self.main_pB_sx.setGeometry(QtCore.QRect(560, 50, 120, 45))
        self.main_pB_sx.setText("")
        self.main_pB_sx.setObjectName("main_pB_sx")
        self.main_pB_td = QtWidgets.QPushButton(Dialog)
        self.main_pB_td.setGeometry(QtCore.QRect(685, 50, 120, 45))
        self.main_pB_td.setText("")
        self.main_pB_td.setObjectName("main_pB_td")
        self.main_pB_qt = QtWidgets.QPushButton(Dialog)
        self.main_pB_qt.setGeometry(QtCore.QRect(810, 50, 120, 45))
        self.main_pB_qt.setText("")
        self.main_pB_qt.setObjectName("main_pB_qt")
        self.pb_fl = QtWidgets.QPushButton(Dialog)
        self.pb_fl.setGeometry(QtCore.QRect(215, 90, 80, 80))
        self.pb_fl.setText("")
        self.pb_fl.setObjectName("pb_fl")
        self.pB_js = QtWidgets.QPushButton(Dialog)
        self.pB_js.setGeometry(QtCore.QRect(295, 90, 80, 80))
        self.pB_js.setText("")
        self.pB_js.setObjectName("pB_js")
        self.pB_lb = QtWidgets.QPushButton(Dialog)
        self.pB_lb.setGeometry(QtCore.QRect(135, 90, 80, 80))
        self.pB_lb.setText("")
        self.pB_lb.setObjectName("pB_lb")
        self.pB_jd = QtWidgets.QPushButton(Dialog)
        self.pB_jd.setGeometry(QtCore.QRect(375, 90, 80, 80))
        self.pB_jd.setText("")
        self.pB_jd.setObjectName("pB_jd")
        self.pB_fg_1 = QtWidgets.QPushButton(Dialog)
        self.pB_fg_1.setGeometry(QtCore.QRect(455, 90, 80, 80))
        self.pB_fg_1.setText("")
        self.pB_fg_1.setObjectName("pB_fg_1")
        self.pB_fg_2 = QtWidgets.QPushButton(Dialog)
        self.pB_fg_2.setGeometry(QtCore.QRect(535, 90, 80, 80))
        self.pB_fg_2.setText("")
        self.pB_fg_2.setObjectName("pB_fg_2")
        self.pB_fg_3 = QtWidgets.QPushButton(Dialog)
        self.pB_fg_3.setGeometry(QtCore.QRect(615, 90, 80, 80))
        self.pB_fg_3.setText("")
        self.pB_fg_3.setObjectName("pB_fg_3")
        self.main_pB_bc = QtWidgets.QPushButton(Dialog)
        self.main_pB_bc.setGeometry(QtCore.QRect(185, 50, 120, 45))
        self.main_pB_bc.setText("")
        self.main_pB_bc.setObjectName("main_pB_bc")
        self.main_mini = QtWidgets.QPushButton(Dialog)
        self.main_mini.setGeometry(QtCore.QRect(1520, 5, 31, 28))
        self.main_mini.setText("")
        self.main_mini.setObjectName("main_mini")
        self.main_close = QtWidgets.QPushButton(Dialog)
        self.main_close.setGeometry(QtCore.QRect(1560, 5, 31, 28))
        self.main_close.setText("")
        self.main_close.setObjectName("main_close")
        self.main_widget1 = QtWidgets.QWidget(Dialog)
        self.main_widget1.setGeometry(QtCore.QRect(0, 0, 191, 31))
        self.main_widget1.setObjectName("main_widget1")
        self.pB_cj = QtWidgets.QPushButton(Dialog)
        self.pB_cj.setGeometry(QtCore.QRect(55, 90, 80, 80))
        self.pB_cj.setText("")
        self.pB_cj.setObjectName("pB_cj")
        self.main_pB_sc = QtWidgets.QPushButton(Dialog)
        self.main_pB_sc.setGeometry(QtCore.QRect(310, 50, 120, 45))
        self.main_pB_sc.setText("")
        self.main_pB_sc.setObjectName("main_pB_sc")
        self.pB_jdjc = QtWidgets.QPushButton(Dialog)
        self.pB_jdjc.setGeometry(QtCore.QRect(695, 90, 80, 80))
        self.pB_jdjc.setText("")
        self.pB_jdjc.setObjectName("pB_jdjc")
        self.pB_fast = QtWidgets.QPushButton(Dialog)
        self.pB_fast.setGeometry(QtCore.QRect(775, 90, 80, 80))
        self.pB_fast.setText("")
        self.pB_fast.setObjectName("pB_fast")
        self.pB_sllj = QtWidgets.QPushButton(Dialog)
        self.pB_sllj.setGeometry(QtCore.QRect(855, 90, 80, 80))
        self.pB_sllj.setText("")
        self.pB_sllj.setObjectName("pB_sllj")
        self.main_pushButton1 = QtWidgets.QPushButton(Dialog)
        self.main_pushButton1.setGeometry(QtCore.QRect(935, 90, 80, 80))
        self.main_pushButton1.setText("")
        self.main_pushButton1.setObjectName("main_pushButton1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
